server:
  port: 8010
  shutdown: graceful

spring:
  main:
    banner-mode: off

# RabbitMQ
rabbitmq:
  sslEnabled: ${RABBITMQ_SSL_ENABLED:false}
  username: ${RABBITMQ_USERNAME:guest}
  password: ${RABBITMQ_PASSWORD:guest}
  host: ${RABBITMQ_HOST:localhost}
  virtualHost: ${RABBITMQ_VIRTUALHOST:test}
  port: ${RABBITMQ_PORT:5672}

# Card Changed Notification
card-changed-notification:
  technicalDeadLetterExchange: example.technical.exchange
  messageTimeToLive: 25000
  maxDeadThreshold: 10
  notificationExchange: example.card-notification
  internationalTransactionLimitationChanged:
    queue: example.card-notification.international-transaction-limitation-changed.queue
    deadLetterQueue: example.card-notification.international-transaction-limitation-changed.dlq
    parkingLotQueue: example.card-notification.international-transaction-limitation-changed.plq
    key: international-transaction-limitation-changed